# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Thay đổi phiên bản Node.js nếu cần

      - name: Install dependencies
        run: |
          cd api # Chuyển đến thư mục dự án Node.js
          npm install                # Cài đặt phụ thuộc cho Node.js
          cd frontend # Chuyển đến thư mục dự án React
          npm install                # Cài đặt phụ thuộc cho React

      - name: Run Node.js and React
        run: |
          cd api/router/index.js  # Chuyển đến thư mục dự án Node.js
          node router/index.js           # Chạy ứng dụng Node.js trong background
          cd fontend # Chuyển đến thư mục dự án React
          npm start                # Chạy ứng dụng React

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
